# Generated by Django 2.2.7 on 2019-12-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('updateTime', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ziten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=128)),
                ('updateTime', models.CharField(max_length=32)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziten_updT_List', to='ZisakuZitenServer.Group')),
            ],
        ),
    ]
